### ISSUE TITLE
Adding consistency

### ISSUE THREAD

**Issue by palkan** [anycable/anycasts#5]
Hacking with Hotwire to support automatic recovery after short connection disruption and during the page load.

- [x] Problems demonstrations and Chrome network throttling feature
- [x] Implementing `.turbo_history`
- [x] Demonstrating AnyCable v1.5 history features

**NOTE:** Record after the RailsConf video is published.

**Comment by nickjj** [comment]
Hi, do you think this feature will be made available in the open source version of AnyCable?

**Comment by palkan** [comment]
It will (it's actually already available in the [1.5.0-preview.1](https://github.com/anycable/anycable-go/releases/tag/v1.5.0.preview1) release). But the current plan is to only support a single-node engine in the OSS version and a distributed, cluster-ready, in PRO.

You can learn more about our plans from this survey (see the TypeForm link): https://github.com/anycable/anycable/discussions/154

**Comment by nickjj** [comment]
Thanks, that makes sense. I really like that model where someone can fully utilize AnyCable on a single server deploy but if they want to scale out then it's expected they go PRO.
